import React from "react";
import ProductsHome from "@/components/Products";
import Head from "next/head";

export default function Home() {
  return <>
    <Head>
      <title>Letmegrab</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/assets/icon.png" />
    </Head>
    <ProductsHome />
  </>
}